# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_layout.ui'
#
# Created: Mon Sep 23 16:00:34 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1264, 807)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.gridLayoutWidget = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtGui.QSplitter(self.gridLayoutWidget)
        self.splitter_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.frame = QtGui.QFrame(self.splitter_2)
        self.frame.setMinimumSize(QtCore.QSize(500, 200))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.matplotlib_display = MatplotlibWidget(self.frame)
        self.matplotlib_display.setMinimumSize(QtCore.QSize(300, 180))
        self.matplotlib_display.setObjectName("matplotlib_display")
        self.gridLayout_6.addWidget(self.matplotlib_display, 1, 0, 1, 1)
        self.cube_info_tab = QtGui.QTabWidget(self.splitter_2)
        self.cube_info_tab.setMinimumSize(QtCore.QSize(300, 0))
        self.cube_info_tab.setToolTip("")
        self.cube_info_tab.setObjectName("cube_info_tab")
        self.print_cube_tab = QtGui.QWidget()
        self.print_cube_tab.setObjectName("print_cube_tab")
        self.gridLayout = QtGui.QGridLayout(self.print_cube_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.print_cube_browser = QtGui.QTextBrowser(self.print_cube_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.print_cube_browser.setFont(font)
        self.print_cube_browser.setStyleSheet("font: 10pt \"Liberation Mono\";\n"
"font: 10pt \"DejaVu Sans Mono\";")
        self.print_cube_browser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.print_cube_browser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.print_cube_browser.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.print_cube_browser.setObjectName("print_cube_browser")
        self.gridLayout.addWidget(self.print_cube_browser, 0, 0, 1, 1)
        self.cube_info_tab.addTab(self.print_cube_tab, "")
        self.print_slice_tab = QtGui.QWidget()
        self.print_slice_tab.setObjectName("print_slice_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.print_slice_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.print_cube_slice_browser = QtGui.QTextBrowser(self.print_slice_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.print_cube_slice_browser.setFont(font)
        self.print_cube_slice_browser.setStyleSheet("font: 10pt \"DejaVu Sans Mono\";")
        self.print_cube_slice_browser.setObjectName("print_cube_slice_browser")
        self.gridLayout_2.addWidget(self.print_cube_slice_browser, 0, 0, 1, 1)
        self.cube_info_tab.addTab(self.print_slice_tab, "")
        self.data_tab = QtGui.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.data_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cube_info_tab.addTab(self.data_tab, "")
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_cube = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.select_cube.setMinimumSize(QtCore.QSize(100, 40))
        self.select_cube.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_cube.setObjectName("select_cube")
        self.verticalLayout.addWidget(self.select_cube)
        self.dim_options_frame = QtGui.QFrame(self.gridLayoutWidget_2)
        self.dim_options_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.dim_options_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dim_options_frame.setObjectName("dim_options_frame")
        self.gridLayout_9 = QtGui.QGridLayout(self.dim_options_frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.axes_dimensions_label = QtGui.QLabel(self.dim_options_frame)
        self.axes_dimensions_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.axes_dimensions_label.setObjectName("axes_dimensions_label")
        self.gridLayout_9.addWidget(self.axes_dimensions_label, 1, 0, 1, 2)
        self.select_dimension_1 = QtGui.QComboBox(self.dim_options_frame)
        self.select_dimension_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_dimension_1.setObjectName("select_dimension_1")
        self.gridLayout_9.addWidget(self.select_dimension_1, 3, 0, 1, 2)
        self.select_dimension_2 = QtGui.QComboBox(self.dim_options_frame)
        self.select_dimension_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_dimension_2.setObjectName("select_dimension_2")
        self.gridLayout_9.addWidget(self.select_dimension_2, 4, 0, 1, 2)
        self.line = QtGui.QFrame(self.dim_options_frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 5, 0, 1, 2)
        self.sliced_dimensions_label = QtGui.QLabel(self.dim_options_frame)
        self.sliced_dimensions_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sliced_dimensions_label.setObjectName("sliced_dimensions_label")
        self.gridLayout_9.addWidget(self.sliced_dimensions_label, 6, 0, 1, 2)
        self.select_sliced_dim = QtGui.QComboBox(self.dim_options_frame)
        self.select_sliced_dim.setEnabled(False)
        self.select_sliced_dim.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_sliced_dim.setObjectName("select_sliced_dim")
        self.gridLayout_9.addWidget(self.select_sliced_dim, 7, 0, 1, 2)
        self.select_slice_combo = QtGui.QComboBox(self.dim_options_frame)
        self.select_slice_combo.setEnabled(False)
        self.select_slice_combo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_slice_combo.setObjectName("select_slice_combo")
        self.gridLayout_9.addWidget(self.select_slice_combo, 9, 0, 1, 1)
        self.select_slice_scroll = QtGui.QScrollBar(self.dim_options_frame)
        self.select_slice_scroll.setEnabled(False)
        self.select_slice_scroll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_slice_scroll.setOrientation(QtCore.Qt.Horizontal)
        self.select_slice_scroll.setObjectName("select_slice_scroll")
        self.gridLayout_9.addWidget(self.select_slice_scroll, 9, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 13, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 11, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 11, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.dim_options_frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_9.addWidget(self.line_2, 10, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 12, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem6, 12, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem7, 13, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem8, 14, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem9, 14, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem10, 15, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem11, 15, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem12, 16, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem13, 16, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem14, 19, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem15, 18, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem16, 17, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem17, 17, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem18, 18, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem19, 19, 1, 1, 1)
        self.verticalLayout.addWidget(self.dim_options_frame)
        self.update_button = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.update_button.setEnabled(False)
        self.update_button.setMinimumSize(QtCore.QSize(0, 40))
        self.update_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.update_button.setObjectName("update_button")
        self.verticalLayout.addWidget(self.update_button)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.plot_menu = QtGui.QDockWidget(MainWindow)
        self.plot_menu.setFeatures(QtGui.QDockWidget.DockWidgetMovable|QtGui.QDockWidget.DockWidgetVerticalTitleBar)
        self.plot_menu.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.plot_menu.setObjectName("plot_menu")
        self.plot_menu_contents = QtGui.QWidget()
        self.plot_menu_contents.setObjectName("plot_menu_contents")
        self.gridLayout_7 = QtGui.QGridLayout(self.plot_menu_contents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plot_type_label = QtGui.QLabel(self.plot_menu_contents)
        self.plot_type_label.setObjectName("plot_type_label")
        self.gridLayout_7.addWidget(self.plot_type_label, 0, 1, 1, 1)
        self.plot_projection_label = QtGui.QLabel(self.plot_menu_contents)
        self.plot_projection_label.setObjectName("plot_projection_label")
        self.gridLayout_7.addWidget(self.plot_projection_label, 0, 3, 1, 1)
        self.color_scheme_label = QtGui.QLabel(self.plot_menu_contents)
        self.color_scheme_label.setObjectName("color_scheme_label")
        self.gridLayout_7.addWidget(self.color_scheme_label, 0, 5, 1, 1)
        self.select_plot_type = QtGui.QComboBox(self.plot_menu_contents)
        self.select_plot_type.setMinimumSize(QtCore.QSize(150, 0))
        self.select_plot_type.setObjectName("select_plot_type")
        self.select_plot_type.addItem("")
        self.select_plot_type.addItem("")
        self.select_plot_type.addItem("")
        self.gridLayout_7.addWidget(self.select_plot_type, 5, 1, 1, 1)
        self.select_projection = QtGui.QComboBox(self.plot_menu_contents)
        self.select_projection.setEnabled(False)
        self.select_projection.setMinimumSize(QtCore.QSize(150, 0))
        self.select_projection.setObjectName("select_projection")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.select_projection.addItem("")
        self.gridLayout_7.addWidget(self.select_projection, 5, 3, 1, 1)
        self.select_colormap = QtGui.QComboBox(self.plot_menu_contents)
        self.select_colormap.setMinimumSize(QtCore.QSize(150, 0))
        self.select_colormap.setObjectName("select_colormap")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.select_colormap.addItem("")
        self.gridLayout_7.addWidget(self.select_colormap, 5, 5, 1, 1)
        self.contour_slider = QtGui.QSlider(self.plot_menu_contents)
        self.contour_slider.setMinimumSize(QtCore.QSize(50, 0))
        self.contour_slider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.contour_slider.setMinimum(1)
        self.contour_slider.setMaximum(50)
        self.contour_slider.setProperty("value", 25)
        self.contour_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contour_slider.setObjectName("contour_slider")
        self.gridLayout_7.addWidget(self.contour_slider, 5, 7, 1, 1)
        self.select_plot_method = QtGui.QComboBox(self.plot_menu_contents)
        self.select_plot_method.setMinimumSize(QtCore.QSize(150, 0))
        self.select_plot_method.setObjectName("select_plot_method")
        self.select_plot_method.addItem("")
        self.select_plot_method.addItem("")
        self.gridLayout_7.addWidget(self.select_plot_method, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.plot_menu_contents)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.contour_label_frame = QtGui.QFrame(self.plot_menu_contents)
        self.contour_label_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.contour_label_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.contour_label_frame.setObjectName("contour_label_frame")
        self.gridLayout_4 = QtGui.QGridLayout(self.contour_label_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.num_contours_label = QtGui.QLabel(self.contour_label_frame)
        self.num_contours_label.setObjectName("num_contours_label")
        self.gridLayout_4.addWidget(self.num_contours_label, 0, 0, 1, 1)
        self.contour_label = QtGui.QLabel(self.contour_label_frame)
        self.contour_label.setObjectName("contour_label")
        self.gridLayout_4.addWidget(self.contour_label, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.contour_label_frame, 0, 7, 1, 1)
        self.select_central_longitude = QtGui.QDoubleSpinBox(self.plot_menu_contents)
        self.select_central_longitude.setEnabled(False)
        self.select_central_longitude.setMinimumSize(QtCore.QSize(150, 0))
        self.select_central_longitude.setMaximum(360.0)
        self.select_central_longitude.setSingleStep(5.0)
        self.select_central_longitude.setObjectName("select_central_longitude")
        self.gridLayout_7.addWidget(self.select_central_longitude, 5, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.plot_menu_contents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 4, 1, 1)
        self.plot_menu.setWidget(self.plot_menu_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.plot_menu)
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_coastlines = QtGui.QAction(MainWindow)
        self.action_coastlines.setCheckable(True)
        self.action_coastlines.setChecked(True)
        self.action_coastlines.setEnabled(False)
        self.action_coastlines.setObjectName("action_coastlines")
        self.action_gridlines = QtGui.QAction(MainWindow)
        self.action_gridlines.setCheckable(True)
        self.action_gridlines.setChecked(True)
        self.action_gridlines.setEnabled(True)
        self.action_gridlines.setObjectName("action_gridlines")
        self.action_country_boundaries = QtGui.QAction(MainWindow)
        self.action_country_boundaries.setCheckable(True)
        self.action_country_boundaries.setEnabled(False)
        self.action_country_boundaries.setObjectName("action_country_boundaries")
        self.action_rivers_and_lakes = QtGui.QAction(MainWindow)
        self.action_rivers_and_lakes.setCheckable(True)
        self.action_rivers_and_lakes.setEnabled(False)
        self.action_rivers_and_lakes.setObjectName("action_rivers_and_lakes")
        self.action_next_slice = QtGui.QAction(MainWindow)
        self.action_next_slice.setEnabled(False)
        self.action_next_slice.setVisible(True)
        self.action_next_slice.setIconVisibleInMenu(False)
        self.action_next_slice.setObjectName("action_next_slice")
        self.action_previous_slice = QtGui.QAction(MainWindow)
        self.action_previous_slice.setEnabled(False)
        self.action_previous_slice.setVisible(True)
        self.action_previous_slice.setObjectName("action_previous_slice")
        self.action_fix_colorbar = QtGui.QAction(MainWindow)
        self.action_fix_colorbar.setCheckable(True)
        self.action_fix_colorbar.setEnabled(False)
        self.action_fix_colorbar.setVisible(False)
        self.action_fix_colorbar.setObjectName("action_fix_colorbar")
        self.action_colorbar = QtGui.QAction(MainWindow)
        self.action_colorbar.setEnabled(False)
        self.action_colorbar.setObjectName("action_colorbar")
        self.action_plot_menu = QtGui.QAction(MainWindow)
        self.action_plot_menu.setCheckable(True)
        self.action_plot_menu.setChecked(True)
        self.action_plot_menu.setObjectName("action_plot_menu")
        self.action_contour_labels = QtGui.QAction(MainWindow)
        self.action_contour_labels.setCheckable(True)
        self.action_contour_labels.setChecked(True)
        self.action_contour_labels.setEnabled(False)
        self.action_contour_labels.setVisible(True)
        self.action_contour_labels.setObjectName("action_contour_labels")
        self.action_full_screen = QtGui.QAction(MainWindow)
        self.action_full_screen.setCheckable(True)
        self.action_full_screen.setVisible(False)
        self.action_full_screen.setObjectName("action_full_screen")
        self.action_load_slices = QtGui.QAction(MainWindow)
        self.action_load_slices.setCheckable(True)
        self.action_load_slices.setEnabled(False)
        self.action_load_slices.setVisible(False)
        self.action_load_slices.setObjectName("action_load_slices")
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_source_code = QtGui.QAction(MainWindow)
        self.action_source_code.setEnabled(False)
        self.action_source_code.setObjectName("action_source_code")
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addAction(self.action_source_code)
        self.toolBar.addAction(self.action_previous_slice)
        self.toolBar.addAction(self.action_next_slice)
        self.toolBar.addAction(self.action_coastlines)
        self.toolBar.addAction(self.action_gridlines)
        self.toolBar.addAction(self.action_contour_labels)
        self.toolBar.addAction(self.action_country_boundaries)
        self.toolBar.addAction(self.action_rivers_and_lakes)
        self.toolBar.addAction(self.action_fix_colorbar)
        self.toolBar.addAction(self.action_colorbar)
        self.toolBar.addAction(self.action_load_slices)
        self.toolBar.addAction(self.action_plot_menu)
        self.toolBar.addAction(self.action_full_screen)
        self.toolBar.addAction(self.action_about)
        self.toolBar.addAction(self.action_exit)

        self.retranslateUi(MainWindow)
        self.cube_info_tab.setCurrentIndex(1)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.contour_slider, QtCore.SIGNAL("valueChanged(int)"), self.contour_label.setNum)
        QtCore.QObject.connect(self.select_slice_combo, QtCore.SIGNAL("currentIndexChanged(int)"), self.select_slice_scroll.setValue)
        QtCore.QObject.connect(self.select_slice_scroll, QtCore.SIGNAL("valueChanged(int)"), self.select_slice_combo.setCurrentIndex)
        QtCore.QObject.connect(self.action_plot_menu, QtCore.SIGNAL("toggled(bool)"), self.plot_menu.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "cubeviz", None, QtGui.QApplication.UnicodeUTF8))
        self.print_cube_tab.setToolTip(QtGui.QApplication.translate("MainWindow", "displays the summary of the loaded cube", None, QtGui.QApplication.UnicodeUTF8))
        self.cube_info_tab.setTabText(self.cube_info_tab.indexOf(self.print_cube_tab), QtGui.QApplication.translate("MainWindow", "Full Cube", None, QtGui.QApplication.UnicodeUTF8))
        self.print_slice_tab.setToolTip(QtGui.QApplication.translate("MainWindow", "displays the summary of the currently plotted slice", None, QtGui.QApplication.UnicodeUTF8))
        self.cube_info_tab.setTabText(self.cube_info_tab.indexOf(self.print_slice_tab), QtGui.QApplication.translate("MainWindow", "Plotted Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.data_tab.setToolTip(QtGui.QApplication.translate("MainWindow", "Displays the data contained within the currently plotted slice", None, QtGui.QApplication.UnicodeUTF8))
        self.cube_info_tab.setTabText(self.cube_info_tab.indexOf(self.data_tab), QtGui.QApplication.translate("MainWindow", "Slice Data", None, QtGui.QApplication.UnicodeUTF8))
        self.select_cube.setToolTip(QtGui.QApplication.translate("MainWindow", "Select which cube to view from the current file", None, QtGui.QApplication.UnicodeUTF8))
        self.axes_dimensions_label.setText(QtGui.QApplication.translate("MainWindow", "Axes Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.select_dimension_1.setToolTip(QtGui.QApplication.translate("MainWindow", "Selects the Dimensions to be plotted against", None, QtGui.QApplication.UnicodeUTF8))
        self.select_dimension_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Selects the Dimensions to be plotted against", None, QtGui.QApplication.UnicodeUTF8))
        self.sliced_dimensions_label.setText(QtGui.QApplication.translate("MainWindow", "Sliced Dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.select_sliced_dim.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the dimension that you wish to take slices through", None, QtGui.QApplication.UnicodeUTF8))
        self.select_slice_combo.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.select_slice_scroll.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.update_button.setToolTip(QtGui.QApplication.translate("MainWindow", "Click this Button to apply changes to the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.update_button.setText(QtGui.QApplication.translate("MainWindow", "Update Image", None, QtGui.QApplication.UnicodeUTF8))
        self.update_button.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_type_label.setText(QtGui.QApplication.translate("MainWindow", "Plot Type", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_projection_label.setText(QtGui.QApplication.translate("MainWindow", "Plot Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.color_scheme_label.setText(QtGui.QApplication.translate("MainWindow", "Colour Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.select_plot_type.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the type of plot to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.select_plot_type.setItemText(0, QtGui.QApplication.translate("MainWindow", "pcolormesh", None, QtGui.QApplication.UnicodeUTF8))
        self.select_plot_type.setItemText(1, QtGui.QApplication.translate("MainWindow", "Filled Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.select_plot_type.setItemText(2, QtGui.QApplication.translate("MainWindow", "Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setToolTip(QtGui.QApplication.translate("MainWindow", "select the map projection to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Plate Carree", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(2, QtGui.QApplication.translate("MainWindow", "Lambert Cylindrical", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(3, QtGui.QApplication.translate("MainWindow", "Mercator", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(4, QtGui.QApplication.translate("MainWindow", "Miller", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(5, QtGui.QApplication.translate("MainWindow", "Orthographic", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(6, QtGui.QApplication.translate("MainWindow", "Robinson", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(7, QtGui.QApplication.translate("MainWindow", "Stereographic", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(8, QtGui.QApplication.translate("MainWindow", "Rotated Pole", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(9, QtGui.QApplication.translate("MainWindow", "OSGB", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(10, QtGui.QApplication.translate("MainWindow", "EuroPP", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(11, QtGui.QApplication.translate("MainWindow", "North Polar Stereo", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(12, QtGui.QApplication.translate("MainWindow", "OSNI", None, QtGui.QApplication.UnicodeUTF8))
        self.select_projection.setItemText(13, QtGui.QApplication.translate("MainWindow", "South Polar Stereo", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the colour scheme to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(0, QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(1, QtGui.QApplication.translate("MainWindow", "brewer_Accent_08", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(2, QtGui.QApplication.translate("MainWindow", "brewer_Blues_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(3, QtGui.QApplication.translate("MainWindow", "brewer_BrBG_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(4, QtGui.QApplication.translate("MainWindow", "brewer_BuGn_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(5, QtGui.QApplication.translate("MainWindow", "brewer_BuPu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(6, QtGui.QApplication.translate("MainWindow", "brewer_Dark2_08", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(7, QtGui.QApplication.translate("MainWindow", "brewer_GnBu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(8, QtGui.QApplication.translate("MainWindow", "brewer_Greens_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(9, QtGui.QApplication.translate("MainWindow", "brewer_Greys_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(10, QtGui.QApplication.translate("MainWindow", "brewer_OrRd_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(11, QtGui.QApplication.translate("MainWindow", "brewer_Oranges_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(12, QtGui.QApplication.translate("MainWindow", "brewer_PRGn_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(13, QtGui.QApplication.translate("MainWindow", "brewer_Paired_12", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(14, QtGui.QApplication.translate("MainWindow", "brewer_Pastel1_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(15, QtGui.QApplication.translate("MainWindow", "brewer_Pastel2_08", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(16, QtGui.QApplication.translate("MainWindow", "brewer_PiYG_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(17, QtGui.QApplication.translate("MainWindow", "brewer_PuBuGn_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(18, QtGui.QApplication.translate("MainWindow", "brewer_PuBu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(19, QtGui.QApplication.translate("MainWindow", "brewer_PuOr_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(20, QtGui.QApplication.translate("MainWindow", "brewer_PuRd_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(21, QtGui.QApplication.translate("MainWindow", "brewer_Purples_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(22, QtGui.QApplication.translate("MainWindow", "brewer_RdBu_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(23, QtGui.QApplication.translate("MainWindow", "brewer_RdGy_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(24, QtGui.QApplication.translate("MainWindow", "brewer_RdPu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(25, QtGui.QApplication.translate("MainWindow", "brewer_RdYlBu_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(26, QtGui.QApplication.translate("MainWindow", "brewer_RdYlGn_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(27, QtGui.QApplication.translate("MainWindow", "brewer_Reds_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(28, QtGui.QApplication.translate("MainWindow", "brewer_Set1_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(29, QtGui.QApplication.translate("MainWindow", "brewer_Set2_08", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(30, QtGui.QApplication.translate("MainWindow", "brewer_Set3_12", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(31, QtGui.QApplication.translate("MainWindow", "brewer_Spectral_11", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(32, QtGui.QApplication.translate("MainWindow", "brewer_YlGnBu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(33, QtGui.QApplication.translate("MainWindow", "brewer_YlGn_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(34, QtGui.QApplication.translate("MainWindow", "brewer_YlOrBr_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(35, QtGui.QApplication.translate("MainWindow", "brewer_YlOrBr_09", None, QtGui.QApplication.UnicodeUTF8))
        self.select_colormap.setItemText(36, QtGui.QApplication.translate("MainWindow", "brewer_YlOrRd_09", None, QtGui.QApplication.UnicodeUTF8))
        self.contour_slider.setToolTip(QtGui.QApplication.translate("MainWindow", "select the number of contours to be plotted", None, QtGui.QApplication.UnicodeUTF8))
        self.select_plot_method.setItemText(0, QtGui.QApplication.translate("MainWindow", "from data array", None, QtGui.QApplication.UnicodeUTF8))
        self.select_plot_method.setItemText(1, QtGui.QApplication.translate("MainWindow", "using quickplot", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Plot Method", None, QtGui.QApplication.UnicodeUTF8))
        self.num_contours_label.setText(QtGui.QApplication.translate("MainWindow", "No. of Contours  = ", None, QtGui.QApplication.UnicodeUTF8))
        self.contour_label.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Central Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setToolTip(QtGui.QApplication.translate("MainWindow", "Click to open a file (shortcut Ctrl + O)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setToolTip(QtGui.QApplication.translate("MainWindow", "Save the current Image (shortcut Ctrl + S)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.action_coastlines.setText(QtGui.QApplication.translate("MainWindow", "Coastlines", None, QtGui.QApplication.UnicodeUTF8))
        self.action_coastlines.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle coastlines drawn on plot (shortcut C)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_coastlines.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_gridlines.setText(QtGui.QApplication.translate("MainWindow", "Gridlines", None, QtGui.QApplication.UnicodeUTF8))
        self.action_gridlines.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle gridlines drawn on plot (shortcut G)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_gridlines.setShortcut(QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.action_country_boundaries.setText(QtGui.QApplication.translate("MainWindow", "Country Boundaries", None, QtGui.QApplication.UnicodeUTF8))
        self.action_country_boundaries.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle Country Boundaries Drawn (shortcut B)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_country_boundaries.setShortcut(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rivers_and_lakes.setText(QtGui.QApplication.translate("MainWindow", "Rivers and Lakes", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rivers_and_lakes.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle Rivers and Lakes drawn (shortcut R)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rivers_and_lakes.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_next_slice.setText(QtGui.QApplication.translate("MainWindow", "Next Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.action_next_slice.setToolTip(QtGui.QApplication.translate("MainWindow", "View the Next Slice (shortcut 6)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_next_slice.setShortcut(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.action_previous_slice.setText(QtGui.QApplication.translate("MainWindow", "Previous Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.action_previous_slice.setToolTip(QtGui.QApplication.translate("MainWindow", "View the Previous Slice (shortcut 4)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_previous_slice.setShortcut(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fix_colorbar.setText(QtGui.QApplication.translate("MainWindow", "Fix Colorbar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fix_colorbar.setShortcut(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.action_colorbar.setText(QtGui.QApplication.translate("MainWindow", "Colorbar Range", None, QtGui.QApplication.UnicodeUTF8))
        self.action_colorbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the range of the colorbar (shortcut O)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_colorbar.setShortcut(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_plot_menu.setText(QtGui.QApplication.translate("MainWindow", "Plot Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.action_plot_menu.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle the Plot Menu (shortcut M)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_plot_menu.setShortcut(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.action_contour_labels.setText(QtGui.QApplication.translate("MainWindow", "Contour Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.action_contour_labels.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle contour lables drawn on plot (shortcut L)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_contour_labels.setShortcut(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_full_screen.setText(QtGui.QApplication.translate("MainWindow", "Full Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_full_screen.setShortcut(QtGui.QApplication.translate("MainWindow", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_load_slices.setText(QtGui.QApplication.translate("MainWindow", "Load All Slices", None, QtGui.QApplication.UnicodeUTF8))
        self.action_load_slices.setToolTip(QtGui.QApplication.translate("MainWindow", "Loads all slices of the cube along the sliced dimension at once. This will then reduce the loading time between slices.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_load_slices.setShortcut(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setToolTip(QtGui.QApplication.translate("MainWindow", "General Information", None, QtGui.QApplication.UnicodeUTF8))
        self.action_source_code.setText(QtGui.QApplication.translate("MainWindow", "Source Code", None, QtGui.QApplication.UnicodeUTF8))
        self.action_source_code.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))

from thea.matplotlib_widget import MatplotlibWidget
